In [1]:
import os
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
path = os.path.join( "..", "data", "processed", "accidents_clean.csv")
accidents_clean = pd.read_csv(path)

In [2]:
# On enlève les variables qui ont peu de poids (V Cramer <0.1) et celles qui ne sont pas informatives 
# ou difficilement exploitables dans un modèle (lat, long)

accidents_clean = accidents_clean.drop(['jour','mois','an','hrmn','sexe',
                                        'lum','int','atm','circ','prof','plan',
                                        'surf','infra','lat', 'long'],axis=1)

In [3]:
# suppression des variables catégorielles redondantes

accidents_clean = accidents_clean.drop(['catu','vma', 'com'],axis=1)

In [4]:
accidents_clean = accidents_clean.drop(['age'],axis=1)

In [7]:
for col in accidents_clean.columns:
    print(f"{col}: {accidents_clean[col].nunique()} valeurs uniques")
    print(accidents_clean[col].unique())
    print("-" * 40)
accidents_clean.nunique()

obs: 18 valeurs uniques
[ 0.  1.  4. 14.  9.  6. 15. 13.  8.  2. 16. 12.  3.  7. 17. 11.  5. 10.]
----------------------------------------
obsm: 7 valeurs uniques
[2. 0. 1. 9. 6. 4. 5.]
----------------------------------------
choc: 10 valeurs uniques
[5. 3. 1. 4. 2. 0. 8. 6. 7. 9.]
----------------------------------------
manv: 27 valeurs uniques
[23 11  0  2 21  1  9 26 15 17  4 12 16 19 13 14  3 10  5 24 18 20  7 22
 25  6  8]
----------------------------------------
motor: 7 valeurs uniques
[1 6 0 3 5 2 4]
----------------------------------------
place: 10 valeurs uniques
[ 2.  1. 10.  3.  4.  7.  9.  6.  8.  5.]
----------------------------------------
grav: 4 valeurs uniques
[2 1 3 4]
----------------------------------------
trajet: 7 valeurs uniques
[0. 5. 9. 1. 4. 2. 3.]
----------------------------------------
dep: 107 valeurs uniques
['93' '92' '94' '87' '69' '38' '34' '13' '988' '976' '974' '972' '2B' '91'
 '86' '83' '80' '78' '77' '76' '72' '71' '67' '66' '64' '60' '51' '50

obs              18
obsm              7
choc             10
manv             27
motor             7
place            10
grav              4
trajet            7
dep             107
agg               2
col               7
catr              8
situ              7
equipements      86
catv_regroup     10
dtype: int64

In [11]:
accidents_clean.to_csv("../data/processed/accidents_preprocessed_v2.csv", index=False)